@startuml
title Login Flow

actor Client

participant AuthController
participant AuthService
participant AuthenticationManager
participant JwtService
participant RefreshTokenService

Client -> AuthController : POST /auth/login\n(usernameOrEmail,password)
activate AuthController

AuthController -> AuthService : login(request)
activate AuthService

AuthService -> AuthenticationManager : authenticate(...)
activate AuthenticationManager

alt Authentication failed

    AuthenticationManager --> AuthService : AuthenticationException
    deactivate AuthenticationManager

    note right of AuthService
      Sai username/password
      Account locked
      Account disabled
      Account not enabled
    end note

    AuthService --> AuthController : Exception

    AuthController --> Client : 401 Unauthorized

else Authentication success

    AuthenticationManager --> AuthService : Authentication
    deactivate AuthenticationManager

    AuthService -> AuthService : extract User from Authentication


    AuthService -> JwtService : generateAccessToken(...)
    activate JwtService

    JwtService --> AuthService : accessToken
    deactivate JwtService

    AuthService -> RefreshTokenService : generateRefreshToken(...)
    activate RefreshTokenService

    RefreshTokenService --> AuthService : refreshToken
    deactivate RefreshTokenService

    AuthService --> AuthController : TokenResponse
    deactivate AuthService

    AuthController --> Client : 200 OK\nTokenResponse
    deactivate AuthController

end

@enduml