CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    metadata JSONB,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE notifications
ADD CONSTRAINT fk_notifications_user FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE,
ADD CONSTRAINT fk_notifications_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE INDEX idx_notifications_user_id ON notifications(recipient_id);
CREATE INDEX idx_notifications_unread_user ON notifications(recipient_id) WHERE is_read = false;


CREATE TRIGGER trg_notifications_updated_at
BEFORE UPDATE ON notifications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();